name: prefect-orion
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - mlflow
  - hyperopt
  - xgboost
  - fastparquet
  - scikit-learn
  - ipykernel 
  - protobuf<4.0
  - pip:
    - prefect==2.0b5